services:
    bugbuster.dlstatsexport.listener.panel:
        class: BugBuster\DlstatsExportBundle\EventListener\ExportPanelListener
        arguments:
          ['@database_connection', '@service_container', '@request_stack']
